name: Update Playlists
on:
  schedule:
    - cron: '0 0 * * *' # Запуск каждый день в полночь
  workflow_dispatch: # Позволяет запускать вручную кнопкой

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          

      - name: Install dependencies
        run: npm install

      - name: Run playlist check
        run: npm run playlist:test

      - name: Run playlist update
        run: npm run playlist:update

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-update playlists"
